---
name: build
"on":
  pull_request:
    branches:
      - main
  push:
    # branches:
    #   - main
  workflow_dispatch:
jobs:
  docker:
    name: Build Alpine Stable NGINX Docker image
    runs-on: ubuntu-20.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # - name: Get latest tag
      #   uses: actions-ecosystem/action-get-latest-tag@v1
      #   id: get-latest-tag
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64, linux/arm/v6, linux/arm/v7, linux/arm64, linux/386, linux/ppc64le, linux/s390x
          file: stable/alpine/Dockerfile
          push: false
          # tags: nginxinc/nginx-unprivileged:${NGINX_MAJOR_STABLE}.${NGINX_MINOR_STABLE}.${NGINX_PATCH_STABLE}-alpine, nginxinc/nginx-unprivileged:stable-alpine, nginxinc/nginx-unprivileged:${NGINX_MAJOR_STABLE}.${NGINX_MINOR_STABLE}-alpine, stable/alpine
          tags: nginxinc/nginx-unprivileged:stable-alpine
